---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=https://jellyfin.openshaw.tech
    volumes:
      - jellyfin:/config
      - /mnt/dozer/media:/data
    ports:
      - 7359:7359/udp #optional discovery
      - 1900:1900/udp #optional DLNA
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.openshaw.tech`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['1','0']  # Prefer RTX 3090 (GPU 1), fallback to P4 (GPU 0)
volumes:
  jellyfin:
    driver: local

networks:
  proxy:
    external: true